<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <!-- Explicitly define platform support to clear the Win2D warning -->
    <Platforms>x86;x64;ARM64</Platforms>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <RuntimeIdentifier Condition=" '$(RuntimeIdentifier)' == '' ">win-x64</RuntimeIdentifier>
    <!-- Ignores the always-true assertion rule so dotnet format can finish without errors -->
    <NoWarn>$(NoWarn);MSTEST0032</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="MSTest.TestAdapter" Version="*" />
    <PackageReference Include="MSTest.TestFramework" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="Moq" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IntVue.csproj" />
  </ItemGroup>

</Project>
